# Connecting to a local CAN device
[backend]
# Use the linux socketcan framework
kind = "socketcan"
# Interface to use. Ensure its up and set to the correct bitrate beforehand
interface = "can0"

# We can also connect to a remote cand
#kind = "net"
#connect = "weblab:2342"


[[listen]]
kind = "tcp"
# Linux automagically binds a v6 socket to v4 as well.
bind = "[::]:2342"

# SCTP is not yet implemented
#[[listen]]
#kind = "sctp"
#bind = "[::]:2342"

[[hook]]
src-addr = 0x60
src-port = 0x03
cooldown = 1000
run = ["./test-hook.sh"]