[workspace]

members = [
    "lab-can-tcp-proto",
    "cand",
    "cand-old",
    "lcp-proto",
    "lcp-client",
    "lcp",
]

[patch.crates-io]
socketcan = { git = "https://github.com/Kilobyte22/socketcan-rs.git", branch = "1.7.0" }
