[package]
name = "lcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
env_logger = "0.10.0"
lcp-client = { path = "../lcp-client" }
log = "0.4.17"
tokio = { version = "1.28.0", features = ["net", "macros", "rt"] }
